web:
  # gin mode = debug or release or test
  mode: "debug"
  port: "8889"
mysql:
  # // dev = open debug log
  log_mode: "dev"
  host: "127.0.0.1"
  port: "3306"
  database: test
  user: root
  password: "1234"
auth:
  # jwt | redis
  active: "redis"
  expireTime: "2h"
  # active = jwt 时候生效
  privateKey: "123456"
redis:
  host: "localhost"
  port: "6379"
  password: ""
rabbitmq: 
  host: "127.0.0.1"
  port: "5672"
  user: "admin"
  password: "aa1234"
  connectNum: 5
  channelNum: 10
log:
  # 环境 dev | prd
  env: dev
  # 输出日志路径
  path: ./log/marketplace_server.log
  # 日志格式 json|console (不填默认console)
  encoding: console
  # 单个文件最大尺寸，默认单位 M  (不填默认100)
  max_size: 10
  # 最大时间，默认单位 day (不填默认不删除备份)
  max_age: 30
  # 最多保留备份个数 (不填默认不删除备份)
  max_backups: 30
